### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by lubangi** [adrianhajdin/project_next_13_ai_prompt_sharing#38]
Everything was working fine, but after adding more than 10 prompts, I got a blink page with this error: Application error: a client-side exception has occurred (see the browser console for more information). in the browser console : typeError: Cannot read properties of undefined (reading 'image')
 at o (page-241b7b2b063c19b3.js:1:1965)
    at rd (2443530c-4218d3c23870e38f.js:9:38892)
    at iw (2443530c-4218d3c23870e38f.js:9:111601)
    at oI (2443530c-4218d3c23870e38f.js:9:89903)
    at 2443530c-4218d3c23870e38f.js:9:89752
    at oA (2443530c-4218d3c23870e38f.js:9:89759)
    at ox (2443530c-4218d3c23870e38f.js:9:87479)
    at oE (2443530c-4218d3c23870e38f.js:9:86343)
    at j (139-3e2f9fb5e42f5af6.js:25:1398)
    at MessagePort.C (139-3e2f9fb5e42f5af6.js:25:1951)

**Comment by Abhisays27** [comment]
Same with me till last night it was perfectly working but now same problem

**Comment by lubangi** [comment]
> Same with me till last night it was perfectly working but now same problem

At some point, I can say shipping an application with the App router is risky!

**Comment by ilyahorski** [comment]
if you get an error, then you need to check in which of the components you are accessing the image variable, there are not many options, most likely it is about getting the user's avatar and most likely the request for getting goes while the session is in an undefined state, in the request to receive data, add a check for the presence of a session, you can also add a check like this session?.user?.image. Let me know if any of this works.

**Comment by devXlalit** [comment]
Try writing "use client" in the front end part it will work!!
