### ISSUE TITLE
Access denied.

### ISSUE THREAD

**Issue by Aakash698** [adrianhajdin/project_next_13_ai_prompt_sharing#50]
MongoServerError: bad auth : authentication failed
    at Connection.onMessage (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:202:26)
    at MessageStream.<anonymous> (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:61:60)
    at MessageStream.emit (node:events:526:28)
    at processIncomingData (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:124:16)
    at MessageStream._write (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' } 
}
Error checking if user exists:  Operation `users.findOne()` buffering timed out after 10000ms
wait  - compiling...
event - compiled successfully in 89 ms (251 modules)
wait  - compiling /api/auth/[...nextauth]/route (client and server)...
event - compiled successfully in 307 ms (541 modules)
wait  - compiling...
event - compiled successfully in 1 ms (541 modules)
MongoServerError: bad auth : authentication failed
    at Connection.onMessage (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:202:26)
    at MessageStream.<anonymous> (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:61:60)
    at MessageStream.emit (node:events:526:28)
    at processIncomingData (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:124:16)
    at MessageStream._write (C:\Users\ashvi\Desktop\Wizard\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:389:12)      
    at _write (node:internal/streams/writable:330:10)
    at MessageStream.Writable.write (node:internal/streams/writable:334:10)
    at TLSSocket.ondata (node:internal/streams/readable:754:22)   
    at TLSSocket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)    
    at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  connectionGeneration: 0,
  [Symbol(errorLabels)]: Set(2) { 'HandshakeError', 'ResetPool' }
}
Error checking if user exists:  Operation `users.findOne()` buffering timed out after 10000ms

**Comment by hungcuongthan** [comment]
in route.js, try callback instead of callbacks
it worked for me

**Comment by Manmit124** [comment]
change callbacks to callback

**Comment by RobItu** [comment]
Changing `callbacks` to `callback` will not work. Check this solution: #52

**Comment by raihanachmad8** [comment]
dont try to change cause async signin and session not be running

**Comment by raihanachmad8** [comment]
this code will solve your problem

`callbacks: {
    async session({ session, token, user }) {
      // indicate to search session if u have a database
      // if (user && user.email) {
      //   console.log(user)
      //   console.log(user.email)
      //   const sessionUser = await Session.findOne({ email: user.email });
      //   if (sessionUser) {
      //     session.user = sessionUser._id.toString();
      //   }
      // }

      return session
    },
    async signIn({ user, account, profile, email, credentials }) {
      try {
        await connectToDB();
        const userExists = await User.findOne({ email: profile?.email });
        // if not, create a new document and save user in MongoDB
        if (userExists === null) {
          await User.create({
            email: profile?.email,
            username: profile?.name.replace(/\s+/g, '').toLowerCase(),
            image: user.image
          })
        }

        return true
      } catch (error) {
        console.log(error);
        return false
      }
      
    } `

**Comment by raihanachmad8** [comment]
> dont try to change cause async signin and session not be running
copy this
```
import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';

import User from '@models/user';
import { connectToDB } from '@utils/database';

const handler = NextAuth({
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
    })
  ],
  callbacks: {
    async session({ session }) {

      const sessionUser = await User.findOne({ email: session.user.email });
      session.user.id = sessionUser._id.toString();

      return session
    },
    async signIn({ user, account, profile, email, credentials }) {
      try {
        await connectToDB();
        const userExists = await User.findOne({ email: profile?.email });
        // if not, create a new document and save user in MongoDB
        if (userExists === null) {
          await User.create({
            email: profile?.email,
            username: profile?.name.replace(/\s+/g, '').toLowerCase(),
            image: user.image
          })
        }

        return true
      } catch (error) {
        console.log(error);
        return false
      }
      
    } 
  }
})

export { handler as GET, handler as POST }
```

**Comment by adekmo** [comment]
> Changing `callbacks` to `callback` will not work. Check this solution: #52

thanks

**Comment by AbdullahTayeh** [comment]
hi, if I want to host it what shall I include in the google.cloud.clonsole, and do I need to change anything in my .env file
